gems: ['jekyll-paginate']
name: Martin Hagerup
description: iOS Developer in Trondheim
meta_description: "Blogging about tech, iOS, programming, and games"

aboutPage: true

markdown: kramdown 
highlighter: rouge

paginate: 20
baseurl: /
domain_name: 'http://mhgr.no'
google_analytics: 'UA-46374019-2'
disqus: true
disqus_shortname: 'martihag'

# Details for the RSS feed generator
url:            'http://mhgr.no'
author:         'Martin Hagerup'
authorTwitter:  'martihag'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
